### ISSUE TITLE
Space is converted to 0

### ISSUE THREAD

**Issue by cricchi79** [ansilove/ansilove.js#10]
The output change spaces to 0 characters, how to fix this error?

**Comment by cricchi79** [comment]
![ansi](https://user-images.githubusercontent.com/46819566/52165487-d005c380-2701-11e9-9184-82f5dd1e8a94.JPG)

**Comment by cricchi79** [comment]
In this case I've used ansilove for view html code of a page, but It create "o" instead of space chars.
Please help me.

**Comment by andyherbert** [comment]
Those are tabs, not spaces. This is also the expected behaviour.
