### ISSUE TITLE
Feature Request: SAUCE tInfoS field support

### ISSUE THREAD

**Issue by sjs** [ansilove/ansilove.js#6]
As of 2013, a new field (tInfoS) was added to SAUCE, that ansilove.js doesn't seem to support.  This field is used for specifying the font that the file should be viewed with.

http://www.acid.org/info/sauce/sauce.htm

**Comment by sjs** [comment]
I have a patch ready for this. I'll submit it as soon as I get a chance.

**Comment by andyherbert** [comment]
Yeah, I should have really updated this when the SAUCE spec was updated. I thought I would wait to see if people would actually start using the extra fields before adding it in, and never actually got around to it.

**Comment by sjs** [comment]
https://github.com/ansilove/ansilove.js/pull/7
